<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Joel Christner</Authors>
    <Company>Joel Christner</Company>
    <Copyright>(c)2026 Joel Christner</Copyright>
    <Product>Radiant</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jchristn/Radiant</RepositoryUrl>
    <PackageProjectUrl>https://github.com/jchristn/Radiant</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.1.0</Version>
    <!-- CS1591: missing XML comment. We document all public members; suppress only for generated/obj noise. -->
  </PropertyGroup>

</Project>
